app.datasource:
   platform: postgres
   driverClassName: org.postgresql.Driver
   jdbc-url: jdbc:postgresql://localhost:5432/test2
   username: postgres
   password: Gauravsagar@26
   

spring:
    flyway:
        baseline-on-migrate: true
        
    jpa:
        open-in-view: false

        
server:
  port : 8082
  
  
  
 
  